import web3 from './web3';

const address='0xB87Edd948B0fD38f3f9865e37A1cF587Ae6B7362';

const abi=[{"constant":true,"inputs":[{"name":"patientID","type":"string"}],"name":"getPatientGender","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view"
,"type":"function"},{"constant":true,"inputs":[{"name":"patientID","type":"string"}],"name":"getPatientAge","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"patientID","type":"string"}],"name":"getPatientID","outputs":[{"name":"","type":"string"}],"payable"
:false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"patientID","type":"string"}],"name":"getPatientPhone","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"patientID","type":"string"}],"name":"getPatientName","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"patientID","type":"string"},{"name":"patientName","type":"string"},{"name":"age","type":"string"},{"name":"gender","type":"string"},{"name":"emailID","type":"string"},{"name":"phoneNumber","type":"string"},{"name":"date","type":"string"},{"name":"p_address","type":"string"}],"name":"setPatientDetails","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":true,"inputs":[{"name":"patientID","type":"string"}],"name":"getPatientEmailID","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"patientID","type":"string"}],"name":"getPatientAddress","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"numpatients","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":
false,"stateMutability":"nonpayable","type":"constructor"}];

export default new web3.eth.Contract(abi,address);